# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui_blue.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, os
from PyQt5 import QtCore, QtGui, QtWidgets

current_dir = os.path.dirname(os.path.abspath(__file__))

resources_dir = os.path.join(current_dir, '..', 'resources')
sys.path.append(resources_dir)

import main_gui_icons_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(884, 665)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("background-color: rgb(202, 238, 236);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.iconsWidget = QtWidgets.QWidget(self.centralwidget)
        self.iconsWidget.setStyleSheet("QWidget{\n"
"    \n"
"    background-color: rgb(202, 238, 236);\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: white;\n"
"    height: 40px;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(44, 49, 60);\n"
"    font-weight: bold;\n"
"}")
        self.iconsWidget.setObjectName("iconsWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.iconsWidget)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.staySmartLogo = QtWidgets.QLabel(self.iconsWidget)
        self.staySmartLogo.setMinimumSize(QtCore.QSize(45, 50))
        self.staySmartLogo.setMaximumSize(QtCore.QSize(40, 50))
        self.staySmartLogo.setText("")
        self.staySmartLogo.setPixmap(QtGui.QPixmap(":/Logo/Logo/Stay Smart Logo 1.png"))
        self.staySmartLogo.setScaledContents(True)
        self.staySmartLogo.setObjectName("staySmartLogo")
        self.horizontalLayout_3.addWidget(self.staySmartLogo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.homeButton = QtWidgets.QPushButton(self.iconsWidget)
        self.homeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/IconsOrange/IconsOrange/#fe8d18/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeButton.setIcon(icon)
        self.homeButton.setIconSize(QtCore.QSize(24, 24))
        self.homeButton.setCheckable(True)
        self.homeButton.setAutoExclusive(True)
        self.homeButton.setObjectName("homeButton")
        self.verticalLayout.addWidget(self.homeButton)
        self.dataAnalysisButton = QtWidgets.QPushButton(self.iconsWidget)
        self.dataAnalysisButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/IconsOrange/IconsOrange/#fe8d18/database.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dataAnalysisButton.setIcon(icon1)
        self.dataAnalysisButton.setIconSize(QtCore.QSize(24, 24))
        self.dataAnalysisButton.setCheckable(True)
        self.dataAnalysisButton.setAutoExclusive(True)
        self.dataAnalysisButton.setObjectName("dataAnalysisButton")
        self.verticalLayout.addWidget(self.dataAnalysisButton)
        self.reportsButton = QtWidgets.QPushButton(self.iconsWidget)
        self.reportsButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/IconsOrange/IconsOrange/#fe8d18/clipboard.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reportsButton.setIcon(icon2)
        self.reportsButton.setIconSize(QtCore.QSize(24, 24))
        self.reportsButton.setCheckable(True)
        self.reportsButton.setAutoExclusive(True)
        self.reportsButton.setObjectName("reportsButton")
        self.verticalLayout.addWidget(self.reportsButton)
        self.notificationsButton = QtWidgets.QPushButton(self.iconsWidget)
        self.notificationsButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/IconsOrange/IconsOrange/#fe8d18/message-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.notificationsButton.setIcon(icon3)
        self.notificationsButton.setIconSize(QtCore.QSize(24, 24))
        self.notificationsButton.setCheckable(True)
        self.notificationsButton.setAutoExclusive(True)
        self.notificationsButton.setObjectName("notificationsButton")
        self.verticalLayout.addWidget(self.notificationsButton)
        self.settingsButton = QtWidgets.QPushButton(self.iconsWidget)
        self.settingsButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/IconsOrange/IconsOrange/#fe8d18/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsButton.setIcon(icon4)
        self.settingsButton.setIconSize(QtCore.QSize(24, 24))
        self.settingsButton.setCheckable(True)
        self.settingsButton.setAutoExclusive(True)
        self.settingsButton.setObjectName("settingsButton")
        self.verticalLayout.addWidget(self.settingsButton)
        spacerItem = QtWidgets.QSpacerItem(20, 258, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.signOutButton = QtWidgets.QPushButton(self.iconsWidget)
        self.signOutButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/IconsOrange/IconsOrange/#fe8d18/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.signOutButton.setIcon(icon5)
        self.signOutButton.setIconSize(QtCore.QSize(24, 24))
        self.signOutButton.setObjectName("signOutButton")
        self.verticalLayout.addWidget(self.signOutButton)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.iconsWidget, 0, 0, 1, 1)
        self.mainWidget = QtWidgets.QWidget(self.centralwidget)
        self.mainWidget.setStyleSheet("background-color: rgb(199, 234, 232);")
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout_5.setContentsMargins(2, 10, 10, 10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.header_widget = QtWidgets.QWidget(self.mainWidget)
        self.header_widget.setStyleSheet("background-color: rgb(202, 238, 236);\n"
"border: none;\n"
"")
        self.header_widget.setObjectName("header_widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.header_widget)
        self.horizontalLayout_4.setContentsMargins(10, 15, 10, 15)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.collapseAndExpandButton = QtWidgets.QPushButton(self.header_widget)
        self.collapseAndExpandButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/IconsOrange/IconsOrange/#fe8d18/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.collapseAndExpandButton.setIcon(icon6)
        self.collapseAndExpandButton.setIconSize(QtCore.QSize(24, 24))
        self.collapseAndExpandButton.setCheckable(True)
        self.collapseAndExpandButton.setAutoExclusive(False)
        self.collapseAndExpandButton.setObjectName("collapseAndExpandButton")
        self.horizontalLayout_4.addWidget(self.collapseAndExpandButton)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchBar = QtWidgets.QLineEdit(self.header_widget)
        self.searchBar.setMinimumSize(QtCore.QSize(200, 24))
        self.searchBar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.searchBar.setObjectName("searchBar")
        self.horizontalLayout.addWidget(self.searchBar)
        self.searchButton = QtWidgets.QPushButton(self.header_widget)
        self.searchButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/IconsOrange/IconsOrange/#fe8d18/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButton.setIcon(icon7)
        self.searchButton.setIconSize(QtCore.QSize(24, 24))
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.profileButton = QtWidgets.QPushButton(self.header_widget)
        self.profileButton.setAutoFillBackground(False)
        self.profileButton.setStyleSheet("border-radius: 40px;")
        self.profileButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/IconsOrange/IconsOrange/#fe8d18/user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profileButton.setIcon(icon8)
        self.profileButton.setIconSize(QtCore.QSize(24, 24))
        self.profileButton.setObjectName("profileButton")
        self.horizontalLayout_4.addWidget(self.profileButton)
        self.verticalLayout_5.addWidget(self.header_widget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.mainWidget)
        self.stackedWidget.setStyleSheet("color: rgb(254, 141, 24);\n"
"background-color: rgb(248, 254, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.placeholderTextForHomePage = QtWidgets.QLabel(self.homePage)
        self.placeholderTextForHomePage.setGeometry(QtCore.QRect(200, 210, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.placeholderTextForHomePage.setFont(font)
        self.placeholderTextForHomePage.setObjectName("placeholderTextForHomePage")
        self.stackedWidget.addWidget(self.homePage)
        self.dataAnalysisPage = QtWidgets.QWidget()
        self.dataAnalysisPage.setObjectName("dataAnalysisPage")
        self.placeholderTextForDataAnalysisPage = QtWidgets.QLabel(self.dataAnalysisPage)
        self.placeholderTextForDataAnalysisPage.setGeometry(QtCore.QRect(170, 210, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.placeholderTextForDataAnalysisPage.setFont(font)
        self.placeholderTextForDataAnalysisPage.setObjectName("placeholderTextForDataAnalysisPage")
        self.stackedWidget.addWidget(self.dataAnalysisPage)
        self.reportsPage = QtWidgets.QWidget()
        self.reportsPage.setObjectName("reportsPage")
        self.placeholderTextForReportsPage = QtWidgets.QLabel(self.reportsPage)
        self.placeholderTextForReportsPage.setGeometry(QtCore.QRect(200, 200, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.placeholderTextForReportsPage.setFont(font)
        self.placeholderTextForReportsPage.setObjectName("placeholderTextForReportsPage")
        self.stackedWidget.addWidget(self.reportsPage)
        self.settingsPage = QtWidgets.QWidget()
        self.settingsPage.setObjectName("settingsPage")
        self.placeholderTextForSettingsPage = QtWidgets.QLabel(self.settingsPage)
        self.placeholderTextForSettingsPage.setGeometry(QtCore.QRect(190, 200, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.placeholderTextForSettingsPage.setFont(font)
        self.placeholderTextForSettingsPage.setObjectName("placeholderTextForSettingsPage")
        self.stackedWidget.addWidget(self.settingsPage)
        self.notificationsPage = QtWidgets.QWidget()
        self.notificationsPage.setObjectName("notificationsPage")
        self.placeholderTextForNotificationsPage = QtWidgets.QLabel(self.notificationsPage)
        self.placeholderTextForNotificationsPage.setGeometry(QtCore.QRect(160, 200, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.placeholderTextForNotificationsPage.setFont(font)
        self.placeholderTextForNotificationsPage.setObjectName("placeholderTextForNotificationsPage")
        self.stackedWidget.addWidget(self.notificationsPage)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.mainWidget, 0, 2, 1, 1)
        self.iconsWithTextWidget = QtWidgets.QWidget(self.centralwidget)
        self.iconsWithTextWidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(202, 238, 236);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: white;\n"
"    text-align: left;\n"
"    height: 40px;\n"
"    padding-left: 10px;\n"
"    border: none;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(44, 49, 60);\n"
"    font-weight: bold;\n"
"}")
        self.iconsWithTextWidget.setObjectName("iconsWithTextWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.iconsWithTextWidget)
        self.verticalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.staySmartLogoWithText = QtWidgets.QLabel(self.iconsWithTextWidget)
        self.staySmartLogoWithText.setMinimumSize(QtCore.QSize(45, 50))
        self.staySmartLogoWithText.setMaximumSize(QtCore.QSize(45, 50))
        self.staySmartLogoWithText.setText("")
        self.staySmartLogoWithText.setPixmap(QtGui.QPixmap(":/Logo/Logo/Stay Smart Logo 1.png"))
        self.staySmartLogoWithText.setScaledContents(True)
        self.staySmartLogoWithText.setObjectName("staySmartLogoWithText")
        self.horizontalLayout_2.addWidget(self.staySmartLogoWithText)
        self.staySmartText = QtWidgets.QLabel(self.iconsWithTextWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.staySmartText.setFont(font)
        self.staySmartText.setStyleSheet("\n"
"color: rgb(38, 184, 238);\n"
"font: 700 12pt \"Segoe UI\";")
        self.staySmartText.setObjectName("staySmartText")
        self.horizontalLayout_2.addWidget(self.staySmartText)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.homeButtonWithText = QtWidgets.QPushButton(self.iconsWithTextWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.homeButtonWithText.setFont(font)
        self.homeButtonWithText.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"font: 700 12pt \"Segoe UI\";")
        self.homeButtonWithText.setIcon(icon)
        self.homeButtonWithText.setIconSize(QtCore.QSize(24, 24))
        self.homeButtonWithText.setCheckable(True)
        self.homeButtonWithText.setAutoExclusive(True)
        self.homeButtonWithText.setObjectName("homeButtonWithText")
        self.verticalLayout_2.addWidget(self.homeButtonWithText)
        self.dataAnalysisButtonWithText = QtWidgets.QPushButton(self.iconsWithTextWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.dataAnalysisButtonWithText.setFont(font)
        self.dataAnalysisButtonWithText.setStyleSheet("font: 700 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.dataAnalysisButtonWithText.setIcon(icon1)
        self.dataAnalysisButtonWithText.setIconSize(QtCore.QSize(24, 24))
        self.dataAnalysisButtonWithText.setCheckable(True)
        self.dataAnalysisButtonWithText.setAutoExclusive(True)
        self.dataAnalysisButtonWithText.setObjectName("dataAnalysisButtonWithText")
        self.verticalLayout_2.addWidget(self.dataAnalysisButtonWithText)
        self.reportsButtonWithText = QtWidgets.QPushButton(self.iconsWithTextWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.reportsButtonWithText.setFont(font)
        self.reportsButtonWithText.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 700 12pt \"Segoe UI\";")
        self.reportsButtonWithText.setIcon(icon2)
        self.reportsButtonWithText.setIconSize(QtCore.QSize(24, 24))
        self.reportsButtonWithText.setCheckable(True)
        self.reportsButtonWithText.setAutoExclusive(True)
        self.reportsButtonWithText.setObjectName("reportsButtonWithText")
        self.verticalLayout_2.addWidget(self.reportsButtonWithText)
        self.notificationsButtonWithText = QtWidgets.QPushButton(self.iconsWithTextWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.notificationsButtonWithText.setFont(font)
        self.notificationsButtonWithText.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 700 12pt \"Segoe UI\";")
        self.notificationsButtonWithText.setIcon(icon3)
        self.notificationsButtonWithText.setIconSize(QtCore.QSize(24, 24))
        self.notificationsButtonWithText.setCheckable(True)
        self.notificationsButtonWithText.setAutoExclusive(True)
        self.notificationsButtonWithText.setObjectName("notificationsButtonWithText")
        self.verticalLayout_2.addWidget(self.notificationsButtonWithText)
        self.settingsButtonWithText = QtWidgets.QPushButton(self.iconsWithTextWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.settingsButtonWithText.setFont(font)
        self.settingsButtonWithText.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 700 12pt \"Segoe UI\";")
        self.settingsButtonWithText.setIcon(icon4)
        self.settingsButtonWithText.setIconSize(QtCore.QSize(24, 24))
        self.settingsButtonWithText.setCheckable(True)
        self.settingsButtonWithText.setAutoExclusive(True)
        self.settingsButtonWithText.setObjectName("settingsButtonWithText")
        self.verticalLayout_2.addWidget(self.settingsButtonWithText)
        spacerItem3 = QtWidgets.QSpacerItem(20, 258, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.signOutButtonWithText = QtWidgets.QPushButton(self.iconsWithTextWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.signOutButtonWithText.setFont(font)
        self.signOutButtonWithText.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 700 12pt \"Segoe UI\";")
        self.signOutButtonWithText.setIcon(icon5)
        self.signOutButtonWithText.setIconSize(QtCore.QSize(24, 24))
        self.signOutButtonWithText.setObjectName("signOutButtonWithText")
        self.verticalLayout_2.addWidget(self.signOutButtonWithText)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.gridLayout.addWidget(self.iconsWithTextWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.collapseAndExpandButton.toggled['bool'].connect(self.iconsWidget.setHidden) # type: ignore
        self.collapseAndExpandButton.toggled['bool'].connect(self.iconsWithTextWidget.setVisible) # type: ignore
        self.settingsButton.toggled['bool'].connect(self.settingsButtonWithText.setChecked) # type: ignore
        self.notificationsButton.toggled['bool'].connect(self.notificationsButtonWithText.setChecked) # type: ignore
        self.reportsButton.toggled['bool'].connect(self.reportsButtonWithText.setChecked) # type: ignore
        self.dataAnalysisButton.toggled['bool'].connect(self.dataAnalysisButtonWithText.setChecked) # type: ignore
        self.homeButton.toggled['bool'].connect(self.homeButtonWithText.setChecked) # type: ignore
        self.homeButtonWithText.toggled['bool'].connect(self.homeButton.setChecked) # type: ignore
        self.dataAnalysisButtonWithText.toggled['bool'].connect(self.dataAnalysisButton.setChecked) # type: ignore
        self.reportsButtonWithText.toggled['bool'].connect(self.reportsButton.setChecked) # type: ignore
        self.notificationsButtonWithText.toggled['bool'].connect(self.notificationsButton.setChecked) # type: ignore
        self.settingsButtonWithText.toggled['bool'].connect(self.settingsButton.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.placeholderTextForHomePage.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#fe8d18;\">Home Page</span></p></body></html>"))
        self.placeholderTextForDataAnalysisPage.setText(_translate("MainWindow", "Data Analysis Page"))
        self.placeholderTextForReportsPage.setText(_translate("MainWindow", "Reports Page"))
        self.placeholderTextForSettingsPage.setText(_translate("MainWindow", "Settings Page"))
        self.placeholderTextForNotificationsPage.setText(_translate("MainWindow", "Notifications Page"))
        self.staySmartText.setText(_translate("MainWindow", "StaySmart"))
        self.homeButtonWithText.setText(_translate("MainWindow", "Home"))
        self.dataAnalysisButtonWithText.setText(_translate("MainWindow", "Data Analysis"))
        self.reportsButtonWithText.setText(_translate("MainWindow", "Reports"))
        self.notificationsButtonWithText.setText(_translate("MainWindow", "Notifications"))
        self.settingsButtonWithText.setText(_translate("MainWindow", "Settings"))
        self.signOutButtonWithText.setText(_translate("MainWindow", "Sign Out"))
import main_gui_icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
